#############################################################################
# Makefile for building: proxy
# Generated by qmake (2.01a) (Qt 4.7.2) on: ?? 5? 8 13:20:17 2011
# Project:  proxy.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile proxy.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = custom_tablewidget_site.cpp \
		main.cpp \
		mainwindow.cpp \
		socketConn.cpp \
		config.cpp \
		getWebPage.cpp \
		dialog.cpp moc_custom_tablewidget_site.cpp \
		moc_mainwindow.cpp \
		moc_socketConn.cpp \
		moc_getWebPage.cpp \
		moc_dialog.cpp \
		qrc_proxy.cpp
OBJECTS       = custom_tablewidget_site.o \
		main.o \
		mainwindow.o \
		socketConn.o \
		config.o \
		getWebPage.o \
		dialog.o \
		moc_custom_tablewidget_site.o \
		moc_mainwindow.o \
		moc_socketConn.o \
		moc_getWebPage.o \
		moc_dialog.o \
		qrc_proxy.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		proxy.pro
QMAKE_TARGET  = proxy
DESTDIR       = 
TARGET        = proxy

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_dialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: proxy.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -o Makefile proxy.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile proxy.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/proxy1.0.0 || $(MKDIR) .tmp/proxy1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/proxy1.0.0/ && $(COPY_FILE) --parents custom_tablewidget_site.h mainwindow.h socketConn.h pError.h config.h getWebPage.h dialog.h .tmp/proxy1.0.0/ && $(COPY_FILE) --parents proxy.qrc .tmp/proxy1.0.0/ && $(COPY_FILE) --parents custom_tablewidget_site.cpp main.cpp mainwindow.cpp socketConn.cpp config.cpp getWebPage.cpp dialog.cpp .tmp/proxy1.0.0/ && $(COPY_FILE) --parents mainwindow.ui dialog.ui .tmp/proxy1.0.0/ && (cd `dirname .tmp/proxy1.0.0` && $(TAR) proxy1.0.0.tar proxy1.0.0 && $(COMPRESS) proxy1.0.0.tar) && $(MOVE) `dirname .tmp/proxy1.0.0`/proxy1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/proxy1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_custom_tablewidget_site.cpp moc_mainwindow.cpp moc_socketConn.cpp moc_getWebPage.cpp moc_dialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_custom_tablewidget_site.cpp moc_mainwindow.cpp moc_socketConn.cpp moc_getWebPage.cpp moc_dialog.cpp
moc_custom_tablewidget_site.cpp: custom_tablewidget_site.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) custom_tablewidget_site.h -o moc_custom_tablewidget_site.cpp

moc_mainwindow.cpp: config.h \
		pError.h \
		dialog.h \
		socketConn.h \
		getWebPage.h \
		mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_socketConn.cpp: pError.h \
		socketConn.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) socketConn.h -o moc_socketConn.cpp

moc_getWebPage.cpp: pError.h \
		getWebPage.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) getWebPage.h -o moc_getWebPage.cpp

moc_dialog.cpp: dialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) dialog.h -o moc_dialog.cpp

compiler_rcc_make_all: qrc_proxy.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_proxy.cpp
qrc_proxy.cpp: proxy.qrc \
		proxy.png
	/usr/bin/rcc -name proxy proxy.qrc -o qrc_proxy.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_dialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_dialog.h
ui_mainwindow.h: mainwindow.ui \
		custom_tablewidget_site.h
	/usr/bin/uic-qt4 mainwindow.ui -o ui_mainwindow.h

ui_dialog.h: dialog.ui
	/usr/bin/uic-qt4 dialog.ui -o ui_dialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

custom_tablewidget_site.o: custom_tablewidget_site.cpp custom_tablewidget_site.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o custom_tablewidget_site.o custom_tablewidget_site.cpp

main.o: main.cpp mainwindow.h \
		config.h \
		pError.h \
		dialog.h \
		socketConn.h \
		getWebPage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		config.h \
		pError.h \
		dialog.h \
		socketConn.h \
		getWebPage.h \
		ui_mainwindow.h \
		custom_tablewidget_site.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

socketConn.o: socketConn.cpp socketConn.h \
		pError.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o socketConn.o socketConn.cpp

config.o: config.cpp config.h \
		pError.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o config.o config.cpp

getWebPage.o: getWebPage.cpp getWebPage.h \
		pError.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o getWebPage.o getWebPage.cpp

dialog.o: dialog.cpp dialog.h \
		ui_dialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dialog.o dialog.cpp

moc_custom_tablewidget_site.o: moc_custom_tablewidget_site.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_custom_tablewidget_site.o moc_custom_tablewidget_site.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_socketConn.o: moc_socketConn.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_socketConn.o moc_socketConn.cpp

moc_getWebPage.o: moc_getWebPage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_getWebPage.o moc_getWebPage.cpp

moc_dialog.o: moc_dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dialog.o moc_dialog.cpp

qrc_proxy.o: qrc_proxy.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_proxy.o qrc_proxy.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

